// Auto-generated by avdl-compiler v1.3.1 (https://github.com/keybase/node-avdl-compiler)
//   Input file: sserver-avdl/sserver.avdl

package searchsrv1

import (
	rpc "github.com/keybase/go-framed-msgpack-rpc"
	context "golang.org/x/net/context"
)

type DocumentID string
type FolderID string
type WriteIndexArg struct {
	TlfID       FolderID   `codec:"tlfID" json:"tlfID"`
	SecureIndex []byte     `codec:"secureIndex" json:"secureIndex"`
	DocID       DocumentID `codec:"docID" json:"docID"`
}

type RenameIndexArg struct {
	TlfID FolderID   `codec:"tlfID" json:"tlfID"`
	Orig  DocumentID `codec:"orig" json:"orig"`
	Curr  DocumentID `codec:"curr" json:"curr"`
}

type DeleteIndexArg struct {
	TlfID FolderID   `codec:"tlfID" json:"tlfID"`
	DocID DocumentID `codec:"docID" json:"docID"`
}

type SearchWordArg struct {
	TlfID     FolderID `codec:"tlfID" json:"tlfID"`
	Trapdoors [][]byte `codec:"trapdoors" json:"trapdoors"`
}

type GetSaltsArg struct {
	TlfID FolderID `codec:"tlfID" json:"tlfID"`
}

type GetSizeArg struct {
	TlfID FolderID `codec:"tlfID" json:"tlfID"`
}

type RegisterTlfArg struct {
	TlfID        FolderID `codec:"tlfID" json:"tlfID"`
	LenSalt      int      `codec:"lenSalt" json:"lenSalt"`
	FpRate       float64  `codec:"fpRate" json:"fpRate"`
	NumUniqWords int64    `codec:"numUniqWords" json:"numUniqWords"`
}

type SearchServerInterface interface {
	WriteIndex(context.Context, WriteIndexArg) error
	RenameIndex(context.Context, RenameIndexArg) error
	DeleteIndex(context.Context, DeleteIndexArg) error
	SearchWord(context.Context, SearchWordArg) ([]DocumentID, error)
	GetSalts(context.Context, FolderID) ([][]byte, error)
	GetSize(context.Context, FolderID) (int64, error)
	RegisterTlf(context.Context, RegisterTlfArg) error
}

func SearchServerProtocol(i SearchServerInterface) rpc.Protocol {
	return rpc.Protocol{
		Name: "searchsrv.1.searchServer",
		Methods: map[string]rpc.ServeHandlerDescription{
			"writeIndex": {
				MakeArg: func() interface{} {
					ret := make([]WriteIndexArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[]WriteIndexArg)
					if !ok {
						err = rpc.NewTypeError((*[]WriteIndexArg)(nil), args)
						return
					}
					err = i.WriteIndex(ctx, (*typedArgs)[0])
					return
				},
				MethodType: rpc.MethodCall,
			},
			"renameIndex": {
				MakeArg: func() interface{} {
					ret := make([]RenameIndexArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[]RenameIndexArg)
					if !ok {
						err = rpc.NewTypeError((*[]RenameIndexArg)(nil), args)
						return
					}
					err = i.RenameIndex(ctx, (*typedArgs)[0])
					return
				},
				MethodType: rpc.MethodCall,
			},
			"deleteIndex": {
				MakeArg: func() interface{} {
					ret := make([]DeleteIndexArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[]DeleteIndexArg)
					if !ok {
						err = rpc.NewTypeError((*[]DeleteIndexArg)(nil), args)
						return
					}
					err = i.DeleteIndex(ctx, (*typedArgs)[0])
					return
				},
				MethodType: rpc.MethodCall,
			},
			"searchWord": {
				MakeArg: func() interface{} {
					ret := make([]SearchWordArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[]SearchWordArg)
					if !ok {
						err = rpc.NewTypeError((*[]SearchWordArg)(nil), args)
						return
					}
					ret, err = i.SearchWord(ctx, (*typedArgs)[0])
					return
				},
				MethodType: rpc.MethodCall,
			},
			"getSalts": {
				MakeArg: func() interface{} {
					ret := make([]GetSaltsArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[]GetSaltsArg)
					if !ok {
						err = rpc.NewTypeError((*[]GetSaltsArg)(nil), args)
						return
					}
					ret, err = i.GetSalts(ctx, (*typedArgs)[0].TlfID)
					return
				},
				MethodType: rpc.MethodCall,
			},
			"getSize": {
				MakeArg: func() interface{} {
					ret := make([]GetSizeArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[]GetSizeArg)
					if !ok {
						err = rpc.NewTypeError((*[]GetSizeArg)(nil), args)
						return
					}
					ret, err = i.GetSize(ctx, (*typedArgs)[0].TlfID)
					return
				},
				MethodType: rpc.MethodCall,
			},
			"registerTlf": {
				MakeArg: func() interface{} {
					ret := make([]RegisterTlfArg, 1)
					return &ret
				},
				Handler: func(ctx context.Context, args interface{}) (ret interface{}, err error) {
					typedArgs, ok := args.(*[]RegisterTlfArg)
					if !ok {
						err = rpc.NewTypeError((*[]RegisterTlfArg)(nil), args)
						return
					}
					err = i.RegisterTlf(ctx, (*typedArgs)[0])
					return
				},
				MethodType: rpc.MethodCall,
			},
		},
	}
}

type SearchServerClient struct {
	Cli rpc.GenericClient
}

func (c SearchServerClient) WriteIndex(ctx context.Context, __arg WriteIndexArg) (err error) {
	err = c.Cli.Call(ctx, "searchsrv.1.searchServer.writeIndex", []interface{}{__arg}, nil)
	return
}

func (c SearchServerClient) RenameIndex(ctx context.Context, __arg RenameIndexArg) (err error) {
	err = c.Cli.Call(ctx, "searchsrv.1.searchServer.renameIndex", []interface{}{__arg}, nil)
	return
}

func (c SearchServerClient) DeleteIndex(ctx context.Context, __arg DeleteIndexArg) (err error) {
	err = c.Cli.Call(ctx, "searchsrv.1.searchServer.deleteIndex", []interface{}{__arg}, nil)
	return
}

func (c SearchServerClient) SearchWord(ctx context.Context, __arg SearchWordArg) (res []DocumentID, err error) {
	err = c.Cli.Call(ctx, "searchsrv.1.searchServer.searchWord", []interface{}{__arg}, &res)
	return
}

func (c SearchServerClient) GetSalts(ctx context.Context, tlfID FolderID) (res [][]byte, err error) {
	__arg := GetSaltsArg{TlfID: tlfID}
	err = c.Cli.Call(ctx, "searchsrv.1.searchServer.getSalts", []interface{}{__arg}, &res)
	return
}

func (c SearchServerClient) GetSize(ctx context.Context, tlfID FolderID) (res int64, err error) {
	__arg := GetSizeArg{TlfID: tlfID}
	err = c.Cli.Call(ctx, "searchsrv.1.searchServer.getSize", []interface{}{__arg}, &res)
	return
}

func (c SearchServerClient) RegisterTlf(ctx context.Context, __arg RegisterTlfArg) (err error) {
	err = c.Cli.Call(ctx, "searchsrv.1.searchServer.registerTlf", []interface{}{__arg}, nil)
	return
}
